version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: mern_backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
      PORT: 5050
      MONGO_URI: "mongodb+srv://admin:kpwl6MRUmf8F0eeZ@backenddb.dnaf1.mongodb.net/mydb"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: mern_frontend
    command: sh -c "npm run build"
    volumes:
      - ./frontend/dist:/app/dist
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: mern_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
